<?php

declare(strict_types=1);

namespace App\Services\Sms;

use RuntimeException;

/**
 * Creates the SMS provider explicitly configured for the deployment.
 *
 * SMS delivery mode and OTP generation are intentionally independent:
 *
 * OTP_FIXED_VALUE=0000
 *     -> predictable OTP for normal Development / QA testing.
 *
 * OTP_FIXED_VALUE=
 *     -> secure random OTP generated by OtpGenerator.
 *
 * sms.provider=log
 *     -> no external SMS delivery.
 *
 * sms.provider=mtalkz
 *     -> real SMS delivery through mTalkz.
 *
 * This allows Development to perform an explicit end-to-end mTalkz
 * integration test without pretending to be Production.
 *
 * Production fixed-OTP protection remains the responsibility of the
 * existing OtpGenerator.
 */
final class SmsProviderFactory
{
    public static function create(): SmsProviderInterface
    {
        /*
         * Provider selection is explicit.
         *
         * Default to "log" rather than "mtalkz" so a missing environment
         * configuration can never accidentally send a real SMS or consume
         * SMS credits.
         */
        $provider =
            mb_strtolower(
                trim(
                    (string) env(
                        'sms.provider',
                        'log'
                    )
                )
            );

        return match ($provider) {
            /*
             * Normal Development / QA mode.
             *
             * The complete application SMS flow executes, but the message is
             * written through LogSmsProvider instead of being sent externally.
             */
            'log' =>
            new LogSmsProvider(),

            /*
             * Real mTalkz delivery.
             *
             * This can intentionally be enabled in Development for end-to-end
             * integration testing by setting:
             *
             * OTP_FIXED_VALUE=
             * sms.provider=mtalkz
             *
             * Production uses the same provider configuration.
             */
            'mtalkz' =>
            new MtalkzSmsProvider(
                service(
                    'curlrequest'
                ),

                trim(
                    (string) env(
                        'sms.apiUrl'
                    )
                ),

                trim(
                    (string) env(
                        'sms.apiKey'
                    )
                ),

                trim(
                    (string) env(
                        'sms.senderId'
                    )
                )
            ),

            default =>
            throw new RuntimeException(
                'Unsupported SMS provider: '
                    . (
                        $provider !== ''
                        ? $provider
                        : '[empty]'
                    )
            ),
        };
    }
}
