-- Canada matrimonial-ready municipality/locality master data
-- Sources: Statistics Canada SGC 2021 census subdivisions and 2021 Census
-- population and dwelling counts.
-- Selection: population >= 2,500; unorganised areas and regional
-- district electoral areas excluded; province-level Other option included.
-- Compatible with the Anandkaraj PostgreSQL master tables on development.
-- Idempotent: safe to execute more than once.

BEGIN;

INSERT INTO master_countries (
    iso_code, name, phone_code, is_active, created_at, updated_at
)
VALUES (
    'CA', 'Canada', '+1', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
ON CONFLICT (iso_code) DO UPDATE
SET name = EXCLUDED.name,
    phone_code = EXCLUDED.phone_code,
    is_active = TRUE,
    updated_at = CURRENT_TIMESTAMP;

WITH canada AS (
    SELECT id FROM master_countries WHERE iso_code = 'CA'
)
INSERT INTO master_states (
    country_id, code, name, display_order, is_active, created_at, updated_at
)
SELECT
    canada.id,
    province_data.code,
    province_data.name,
    province_data.display_order,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM canada
CROSS JOIN (
    VALUES
        ('NL', 'Newfoundland and Labrador', 1),
        ('PE', 'Prince Edward Island', 2),
        ('NS', 'Nova Scotia', 3),
        ('NB', 'New Brunswick', 4),
        ('QC', 'Quebec', 5),
        ('ON', 'Ontario', 6),
        ('MB', 'Manitoba', 7),
        ('SK', 'Saskatchewan', 8),
        ('AB', 'Alberta', 9),
        ('BC', 'British Columbia', 10),
        ('YT', 'Yukon', 11),
        ('NT', 'Northwest Territories', 12),
        ('NU', 'Nunavut', 13)
) AS province_data (code, name, display_order)
ON CONFLICT (country_id, code) DO UPDATE
SET name = EXCLUDED.name,
    display_order = EXCLUDED.display_order,
    is_active = TRUE,
    updated_at = CURRENT_TIMESTAMP;

-- Deactivate older Canada locality rows first. Existing foreign-key references
-- remain valid; the curated rows below are reactivated by their upsert.
UPDATE master_cities city
SET is_active = FALSE,
    updated_at = CURRENT_TIMESTAMP
FROM master_states state
INNER JOIN master_countries country
    ON country.id = state.country_id
WHERE city.state_id = state.id
  AND country.iso_code = 'CA';

INSERT INTO master_cities (
    state_id, name, display_order, is_active, created_at, updated_at
)
SELECT
    state.id,
    city_data.name,
    city_data.display_order,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM (
    VALUES
        ('NL', 'Bay Roberts', 1),
        ('NL', 'Bishop''s Falls', 2),
        ('NL', 'Bonavista', 3),
        ('NL', 'Botwood', 4),
        ('NL', 'Carbonear', 5),
        ('NL', 'Channel-Port aux Basques', 6),
        ('NL', 'Clarenville', 7),
        ('NL', 'Conception Bay South', 8),
        ('NL', 'Corner Brook', 9),
        ('NL', 'Deer Lake', 10),
        ('NL', 'Gander', 11),
        ('NL', 'Grand Falls-Windsor', 12),
        ('NL', 'Happy Valley-Goose Bay', 13),
        ('NL', 'Harbour Grace', 14),
        ('NL', 'Labrador City', 15),
        ('NL', 'Lewisporte', 16),
        ('NL', 'Marystown', 17),
        ('NL', 'Mount Pearl', 18),
        ('NL', 'Paradise', 19),
        ('NL', 'Pasadena', 20),
        ('NL', 'Placentia', 21),
        ('NL', 'Portugal Cove-St. Philip''s', 22),
        ('NL', 'Spaniard''s Bay', 23),
        ('NL', 'Springdale', 24),
        ('NL', 'St. John''s', 25),
        ('NL', 'Stephenville', 26),
        ('NL', 'Torbay', 27),
        ('NL', 'Other', 32767),
        ('PE', 'Charlottetown', 1),
        ('PE', 'Cornwall', 2),
        ('PE', 'Kensington, Part 1', 3),
        ('PE', 'New Glasgow', 4),
        ('PE', 'North Shore', 5),
        ('PE', 'O''Leary', 6),
        ('PE', 'Stratford', 7),
        ('PE', 'Summerside', 8),
        ('PE', 'Three Rivers', 9),
        ('PE', 'West River', 10),
        ('PE', 'Other', 32767),
        ('NS', 'Amherst', 1),
        ('NS', 'Annapolis, Subd. A', 2),
        ('NS', 'Annapolis, Subd. B', 3),
        ('NS', 'Annapolis, Subd. C', 4),
        ('NS', 'Annapolis, Subd. D', 5),
        ('NS', 'Antigonish', 6),
        ('NS', 'Antigonish, Subd. A', 7),
        ('NS', 'Antigonish, Subd. B', 8),
        ('NS', 'Argyle', 9),
        ('NS', 'Barrington', 10),
        ('NS', 'Bridgewater', 11),
        ('NS', 'Cape Breton', 12),
        ('NS', 'Chester', 13),
        ('NS', 'Clare', 14),
        ('NS', 'Colchester, Subd. A', 15),
        ('NS', 'Colchester, Subd. B', 16),
        ('NS', 'Colchester, Subd. C', 17),
        ('NS', 'Cumberland, Subd. A', 18),
        ('NS', 'Cumberland, Subd. B', 19),
        ('NS', 'Cumberland, Subd. C', 20),
        ('NS', 'Cumberland, Subd. D', 21),
        ('NS', 'Digby', 22),
        ('NS', 'East Hants', 23),
        ('NS', 'Eskasoni 3', 24),
        ('NS', 'Guysborough', 25),
        ('NS', 'Halifax', 26),
        ('NS', 'Indian Brook 14', 27),
        ('NS', 'Inverness, Subd. A', 28),
        ('NS', 'Inverness, Subd. B', 29),
        ('NS', 'Inverness, Subd. C', 30),
        ('NS', 'Kentville', 31),
        ('NS', 'Kings, Subd. A', 32),
        ('NS', 'Kings, Subd. B', 33),
        ('NS', 'Kings, Subd. C', 34),
        ('NS', 'Kings, Subd. D', 35),
        ('NS', 'Lunenburg', 36),
        ('NS', 'New Glasgow', 37),
        ('NS', 'Pictou', 38),
        ('NS', 'Pictou, Subd. A', 39),
        ('NS', 'Pictou, Subd. B', 40),
        ('NS', 'Pictou, Subd. C', 41),
        ('NS', 'Port Hawkesbury', 42),
        ('NS', 'Queens', 43),
        ('NS', 'Richmond, Subd. A', 44),
        ('NS', 'Richmond, Subd. C', 45),
        ('NS', 'Shelburne', 46),
        ('NS', 'Stellarton', 47),
        ('NS', 'Truro', 48),
        ('NS', 'Victoria, Subd. A', 49),
        ('NS', 'Victoria, Subd. B', 50),
        ('NS', 'West Hants', 51),
        ('NS', 'Westville', 52),
        ('NS', 'Wolfville', 53),
        ('NS', 'Yarmouth [SGC 1202004]', 54),
        ('NS', 'Yarmouth [SGC 1202006]', 55),
        ('NS', 'Other', 32767),
        ('NB', 'Alnwick', 1),
        ('NB', 'Atholville', 2),
        ('NB', 'Bathurst [SGC 1315008]', 3),
        ('NB', 'Bathurst [SGC 1315011]', 4),
        ('NB', 'Beaubassin East / Beaubassin-est', 5),
        ('NB', 'Beresford [SGC 1315012]', 6),
        ('NB', 'Beresford [SGC 1315015]', 7),
        ('NB', 'Bouctouche', 8),
        ('NB', 'Bright', 9),
        ('NB', 'Burton', 10),
        ('NB', 'Campbellton', 11),
        ('NB', 'Caraquet', 12),
        ('NB', 'Cocagne', 13),
        ('NB', 'Coverdale', 14),
        ('NB', 'Dalhousie', 15),
        ('NB', 'Dieppe', 16),
        ('NB', 'Douglas', 17),
        ('NB', 'Dundas', 18),
        ('NB', 'Edmundston', 19),
        ('NB', 'Fredericton', 20),
        ('NB', 'Grand Bay-Westfield', 21),
        ('NB', 'Grand Falls / Grand-Sault', 22),
        ('NB', 'Grand Manan', 23),
        ('NB', 'Hampton [SGC 1305006]', 24),
        ('NB', 'Hampton [SGC 1305007]', 25),
        ('NB', 'Hanwell', 26),
        ('NB', 'Haut-Madawaska', 27),
        ('NB', 'Kingsclear', 28),
        ('NB', 'Kingston', 29),
        ('NB', 'Lincoln', 30),
        ('NB', 'Memramcook', 31),
        ('NB', 'Miramichi', 32),
        ('NB', 'Moncton [SGC 1307019]', 33),
        ('NB', 'Moncton [SGC 1307022]', 34),
        ('NB', 'New Maryland [SGC 1310001]', 35),
        ('NB', 'New Maryland [SGC 1310002]', 36),
        ('NB', 'Oromocto', 37),
        ('NB', 'Quispamsis', 38),
        ('NB', 'Riverview', 39),
        ('NB', 'Rothesay', 40),
        ('NB', 'Sackville', 41),
        ('NB', 'Saint John', 42),
        ('NB', 'Saint Marys', 43),
        ('NB', 'Salisbury', 44),
        ('NB', 'Shediac [SGC 1307016]', 45),
        ('NB', 'Shediac [SGC 1307052]', 46),
        ('NB', 'Shippagan [SGC 1315029]', 47),
        ('NB', 'Shippagan [SGC 1315031]', 48),
        ('NB', 'Simonds', 49),
        ('NB', 'St. Stephen', 50),
        ('NB', 'Studholm', 51),
        ('NB', 'Sussex [SGC 1305021]', 52),
        ('NB', 'Sussex [SGC 1305022]', 53),
        ('NB', 'Tracadie', 54),
        ('NB', 'Wakefield', 55),
        ('NB', 'Wellington', 56),
        ('NB', 'Woodstock', 57),
        ('NB', 'Other', 32767),
        ('QC', 'Acton Vale', 1),
        ('QC', 'Adstock', 2),
        ('QC', 'Alma', 3),
        ('QC', 'Amos', 4),
        ('QC', 'Amqui', 5),
        ('QC', 'Ange-Gardien', 6),
        ('QC', 'Ascot Corner', 7),
        ('QC', 'Baie-Comeau', 8),
        ('QC', 'Baie-D''Urfé', 9),
        ('QC', 'Baie-Saint-Paul', 10),
        ('QC', 'Beaconsfield', 11),
        ('QC', 'Beauceville', 12),
        ('QC', 'Beauharnois', 13),
        ('QC', 'Beaumont', 14),
        ('QC', 'Beaupré', 15),
        ('QC', 'Bedford', 16),
        ('QC', 'Beloeil', 17),
        ('QC', 'Berthierville', 18),
        ('QC', 'Blainville', 19),
        ('QC', 'Bois-des-Filion', 20),
        ('QC', 'Boisbriand', 21),
        ('QC', 'Boischatel', 22),
        ('QC', 'Bonaventure', 23),
        ('QC', 'Boucherville', 24),
        ('QC', 'Bromont', 25),
        ('QC', 'Brossard', 26),
        ('QC', 'Brownsburg-Chatham', 27),
        ('QC', 'Bécancour', 28),
        ('QC', 'Candiac', 29),
        ('QC', 'Cantley', 30),
        ('QC', 'Cap-Chat', 31),
        ('QC', 'Cap-Saint-Ignace', 32),
        ('QC', 'Cap-Santé', 33),
        ('QC', 'Carignan', 34),
        ('QC', 'Carleton-sur-Mer', 35),
        ('QC', 'Chambly', 36),
        ('QC', 'Chandler', 37),
        ('QC', 'Charlemagne', 38),
        ('QC', 'Chelsea', 39),
        ('QC', 'Chertsey', 40),
        ('QC', 'Chibougamau', 41),
        ('QC', 'Chisasibi', 42),
        ('QC', 'Château-Richer', 43),
        ('QC', 'Châteauguay', 44),
        ('QC', 'Clermont', 45),
        ('QC', 'Coaticook', 46),
        ('QC', 'Compton', 47),
        ('QC', 'Contrecoeur', 48),
        ('QC', 'Cookshire-Eaton', 49),
        ('QC', 'Coteau-du-Lac', 50),
        ('QC', 'Cowansville', 51),
        ('QC', 'Crabtree', 52),
        ('QC', 'Côte-Saint-Luc', 53),
        ('QC', 'Danville', 54),
        ('QC', 'Delson', 55),
        ('QC', 'Deux-Montagnes', 56),
        ('QC', 'Dolbeau-Mistassini', 57),
        ('QC', 'Dollard-Des Ormeaux', 58),
        ('QC', 'Donnacona', 59),
        ('QC', 'Dorval', 60),
        ('QC', 'Drummondville', 61),
        ('QC', 'Dunham', 62),
        ('QC', 'Dégelis', 63),
        ('QC', 'East Angus', 64),
        ('QC', 'Eeyou Istchee Baie-James', 65),
        ('QC', 'Farnham', 66),
        ('QC', 'Ferme-Neuve', 67),
        ('QC', 'Forestville', 68),
        ('QC', 'Gaspé', 69),
        ('QC', 'Gatineau', 70),
        ('QC', 'Granby', 71),
        ('QC', 'Grande-Rivière', 72),
        ('QC', 'Grenville-sur-la-Rouge', 73),
        ('QC', 'Hampstead', 74),
        ('QC', 'Havre-Saint-Pierre', 75),
        ('QC', 'Hudson', 76),
        ('QC', 'Huntingdon', 77),
        ('QC', 'Hébertville', 78),
        ('QC', 'Joliette', 79),
        ('QC', 'Kirkland', 80),
        ('QC', 'Kuujjuaq', 81),
        ('QC', 'L''Ancienne-Lorette', 82),
        ('QC', 'L''Ange-Gardien [SGC 2421040]', 83),
        ('QC', 'L''Ange-Gardien [SGC 2482005]', 84),
        ('QC', 'L''Assomption', 85),
        ('QC', 'L''Islet', 86),
        ('QC', 'L''Épiphanie', 87),
        ('QC', 'L''Île-Perrot', 88),
        ('QC', 'La Malbaie', 89),
        ('QC', 'La Pocatière', 90),
        ('QC', 'La Prairie', 91),
        ('QC', 'La Présentation', 92),
        ('QC', 'La Pêche', 93),
        ('QC', 'La Sarre', 94),
        ('QC', 'La Tuque', 95),
        ('QC', 'Labelle', 96),
        ('QC', 'Lac-Beauport', 97),
        ('QC', 'Lac-Brome', 98),
        ('QC', 'Lac-des-Écorces', 99),
        ('QC', 'Lac-Etchemin', 100),
        ('QC', 'Lac-Mégantic', 101),
        ('QC', 'Lachute', 102),
        ('QC', 'Lacolle', 103),
        ('QC', 'Lanoraie', 104),
        ('QC', 'Laurier-Station', 105),
        ('QC', 'Laval', 106),
        ('QC', 'Lavaltrie', 107),
        ('QC', 'Les Coteaux', 108),
        ('QC', 'Les Cèdres', 109),
        ('QC', 'Les Îles-de-la-Madeleine', 110),
        ('QC', 'Longueuil', 111),
        ('QC', 'Lorraine', 112),
        ('QC', 'Louiseville', 113),
        ('QC', 'Lévis', 114),
        ('QC', 'Macamic', 115),
        ('QC', 'Magog', 116),
        ('QC', 'Malartic', 117),
        ('QC', 'Maniwaki', 118),
        ('QC', 'Maria', 119),
        ('QC', 'Marieville', 120),
        ('QC', 'Mascouche', 121),
        ('QC', 'Matane', 122),
        ('QC', 'McMasterville', 123),
        ('QC', 'Mercier', 124),
        ('QC', 'Mirabel', 125),
        ('QC', 'Mistissini', 126),
        ('QC', 'Mont-Joli', 127),
        ('QC', 'Mont-Laurier', 128),
        ('QC', 'Mont-Royal', 129),
        ('QC', 'Mont-Saint-Grégoire', 130),
        ('QC', 'Mont-Saint-Hilaire', 131),
        ('QC', 'Mont-Tremblant', 132),
        ('QC', 'Montmagny', 133),
        ('QC', 'Montréal', 134),
        ('QC', 'Montréal-Est', 135),
        ('QC', 'Montréal-Ouest', 136),
        ('QC', 'Morin-Heights', 137),
        ('QC', 'Métabetchouan--Lac-à-la-Croix', 138),
        ('QC', 'Napierville', 139),
        ('QC', 'Neuville', 140),
        ('QC', 'New Richmond', 141),
        ('QC', 'Nicolet', 142),
        ('QC', 'Normandin', 143),
        ('QC', 'Notre-Dame-de-l''Île-Perrot', 144),
        ('QC', 'Notre-Dame-de-Lourdes', 145),
        ('QC', 'Notre-Dame-des-Prairies', 146),
        ('QC', 'Notre-Dame-du-Mont-Carmel', 147),
        ('QC', 'Oka', 148),
        ('QC', 'Orford', 149),
        ('QC', 'Ormstown', 150),
        ('QC', 'Otterburn Park', 151),
        ('QC', 'Paspébiac', 152),
        ('QC', 'Percé', 153),
        ('QC', 'Piedmont', 154),
        ('QC', 'Pincourt', 155),
        ('QC', 'Plessisville [SGC 2432040]', 156),
        ('QC', 'Plessisville [SGC 2432045]', 157),
        ('QC', 'Pointe-Calumet', 158),
        ('QC', 'Pointe-Claire', 159),
        ('QC', 'Pont-Rouge', 160),
        ('QC', 'Pontiac', 161),
        ('QC', 'Port-Cartier', 162),
        ('QC', 'Portneuf', 163),
        ('QC', 'Princeville', 164),
        ('QC', 'Prévost', 165),
        ('QC', 'Québec', 166),
        ('QC', 'Rawdon', 167),
        ('QC', 'Repentigny', 168),
        ('QC', 'Richelieu', 169),
        ('QC', 'Richmond', 170),
        ('QC', 'Rigaud', 171),
        ('QC', 'Rimouski', 172),
        ('QC', 'Rivière-du-Loup', 173),
        ('QC', 'Rivière-Rouge', 174),
        ('QC', 'Roberval', 175),
        ('QC', 'Rosemère', 176),
        ('QC', 'Rougemont', 177),
        ('QC', 'Rouyn-Noranda', 178),
        ('QC', 'Roxton Pond', 179),
        ('QC', 'Saguenay', 180),
        ('QC', 'Saint-Adolphe-d''Howard', 181),
        ('QC', 'Saint-Agapit', 182),
        ('QC', 'Saint-Alexandre', 183),
        ('QC', 'Saint-Alexis-des-Monts', 184),
        ('QC', 'Saint-Alphonse-de-Granby', 185),
        ('QC', 'Saint-Alphonse-Rodriguez', 186),
        ('QC', 'Saint-Amable', 187),
        ('QC', 'Saint-Ambroise', 188),
        ('QC', 'Saint-Ambroise-de-Kildare', 189),
        ('QC', 'Saint-Anaclet-de-Lessard', 190),
        ('QC', 'Saint-André-Avellin', 191),
        ('QC', 'Saint-André-d''Argenteuil', 192),
        ('QC', 'Saint-Anicet', 193),
        ('QC', 'Saint-Anselme', 194),
        ('QC', 'Saint-Antonin', 195),
        ('QC', 'Saint-Apollinaire', 196),
        ('QC', 'Saint-Augustin-de-Desmaures', 197),
        ('QC', 'Saint-Basile', 198),
        ('QC', 'Saint-Basile-le-Grand', 199),
        ('QC', 'Saint-Bernard', 200),
        ('QC', 'Saint-Boniface', 201),
        ('QC', 'Saint-Bruno', 202),
        ('QC', 'Saint-Bruno-de-Montarville', 203),
        ('QC', 'Saint-Calixte', 204),
        ('QC', 'Saint-Charles-Borromée', 205),
        ('QC', 'Saint-Charles-de-Bellechasse', 206),
        ('QC', 'Saint-Christophe-d''Arthabaska', 207),
        ('QC', 'Saint-Chrysostome', 208),
        ('QC', 'Saint-Colomban', 209),
        ('QC', 'Saint-Constant', 210),
        ('QC', 'Saint-Cyrille-de-Wendover', 211),
        ('QC', 'Saint-Césaire', 212),
        ('QC', 'Saint-Côme', 213),
        ('QC', 'Saint-Côme--Linière', 214),
        ('QC', 'Saint-David-de-Falardeau', 215),
        ('QC', 'Saint-Denis-de-Brompton', 216),
        ('QC', 'Saint-Dominique', 217),
        ('QC', 'Saint-Donat', 218),
        ('QC', 'Saint-Elzéar', 219),
        ('QC', 'Saint-Eustache', 220),
        ('QC', 'Saint-Faustin--Lac-Carré', 221),
        ('QC', 'Saint-Ferréol-les-Neiges', 222),
        ('QC', 'Saint-Félicien', 223),
        ('QC', 'Saint-Félix-de-Valois', 224),
        ('QC', 'Saint-Gabriel', 225),
        ('QC', 'Saint-Gabriel-de-Brandon', 226),
        ('QC', 'Saint-Gabriel-de-Valcartier', 227),
        ('QC', 'Saint-Georges', 228),
        ('QC', 'Saint-Germain-de-Grantham', 229),
        ('QC', 'Saint-Gilles', 230),
        ('QC', 'Saint-Henri', 231),
        ('QC', 'Saint-Hippolyte', 232),
        ('QC', 'Saint-Honoré', 233),
        ('QC', 'Saint-Hyacinthe', 234),
        ('QC', 'Saint-Isidore [SGC 2426063]', 235),
        ('QC', 'Saint-Isidore [SGC 2467040]', 236),
        ('QC', 'Saint-Jacques', 237),
        ('QC', 'Saint-Jean-Baptiste', 238),
        ('QC', 'Saint-Jean-de-Matha', 239),
        ('QC', 'Saint-Jean-Port-Joli', 240),
        ('QC', 'Saint-Jean-sur-Richelieu', 241),
        ('QC', 'Saint-Joseph-de-Beauce', 242),
        ('QC', 'Saint-Joseph-du-Lac', 243),
        ('QC', 'Saint-Jérôme', 244),
        ('QC', 'Saint-Lambert', 245),
        ('QC', 'Saint-Lambert-de-Lauzon', 246),
        ('QC', 'Saint-Lazare', 247),
        ('QC', 'Saint-Liboire', 248),
        ('QC', 'Saint-Lin--Laurentides', 249),
        ('QC', 'Saint-Léonard-d''Aston', 250),
        ('QC', 'Saint-Marc-des-Carrières', 251),
        ('QC', 'Saint-Martin', 252),
        ('QC', 'Saint-Mathias-sur-Richelieu', 253),
        ('QC', 'Saint-Mathieu-de-Beloeil', 254),
        ('QC', 'Saint-Maurice', 255),
        ('QC', 'Saint-Michel', 256),
        ('QC', 'Saint-Pascal', 257),
        ('QC', 'Saint-Paul', 258),
        ('QC', 'Saint-Paul-d''Abbotsford', 259),
        ('QC', 'Saint-Philippe', 260),
        ('QC', 'Saint-Pie', 261),
        ('QC', 'Saint-Prime', 262),
        ('QC', 'Saint-Prosper', 263),
        ('QC', 'Saint-Raymond', 264),
        ('QC', 'Saint-Roch-de-l''Achigan', 265),
        ('QC', 'Saint-Roch-de-Richelieu', 266),
        ('QC', 'Saint-Rémi', 267),
        ('QC', 'Saint-Sauveur', 268),
        ('QC', 'Saint-Sulpice', 269),
        ('QC', 'Saint-Thomas', 270),
        ('QC', 'Saint-Tite', 271),
        ('QC', 'Saint-Zotique', 272),
        ('QC', 'Saint-Étienne-des-Grès', 273),
        ('QC', 'Sainte-Adèle', 274),
        ('QC', 'Sainte-Agathe-des-Monts', 275),
        ('QC', 'Sainte-Anne-de-Beaupré', 276),
        ('QC', 'Sainte-Anne-de-Bellevue', 277),
        ('QC', 'Sainte-Anne-de-Sorel', 278),
        ('QC', 'Sainte-Anne-des-Lacs', 279),
        ('QC', 'Sainte-Anne-des-Monts', 280),
        ('QC', 'Sainte-Anne-des-Plaines', 281),
        ('QC', 'Sainte-Brigitte-de-Laval', 282),
        ('QC', 'Sainte-Catherine', 283),
        ('QC', 'Sainte-Catherine-de-Hatley', 284),
        ('QC', 'Sainte-Catherine-de-la-Jacques-Cartier', 285),
        ('QC', 'Sainte-Claire', 286),
        ('QC', 'Sainte-Clotilde', 287),
        ('QC', 'Sainte-Croix', 288),
        ('QC', 'Sainte-Julie', 289),
        ('QC', 'Sainte-Julienne', 290),
        ('QC', 'Sainte-Luce', 291),
        ('QC', 'Sainte-Marguerite-du-Lac-Masson', 292),
        ('QC', 'Sainte-Marie', 293),
        ('QC', 'Sainte-Marie-Madeleine', 294),
        ('QC', 'Sainte-Marthe-sur-le-Lac', 295),
        ('QC', 'Sainte-Martine', 296),
        ('QC', 'Sainte-Mélanie', 297),
        ('QC', 'Sainte-Sophie', 298),
        ('QC', 'Sainte-Thérèse', 299),
        ('QC', 'Salaberry-de-Valleyfield', 300),
        ('QC', 'Scott', 301),
        ('QC', 'Senneterre', 302),
        ('QC', 'Sept-Îles', 303),
        ('QC', 'Shannon', 304),
        ('QC', 'Shawinigan', 305),
        ('QC', 'Shefford', 306),
        ('QC', 'Sherbrooke', 307),
        ('QC', 'Sorel-Tracy', 308),
        ('QC', 'Stanstead', 309),
        ('QC', 'Stoke', 310),
        ('QC', 'Stoneham-et-Tewkesbury', 311),
        ('QC', 'Sutton', 312),
        ('QC', 'Terrebonne', 313),
        ('QC', 'Thetford Mines', 314),
        ('QC', 'Thurso', 315),
        ('QC', 'Trois-Pistoles', 316),
        ('QC', 'Trois-Rivières', 317),
        ('QC', 'Témiscouata-sur-le-Lac', 318),
        ('QC', 'Val-d''Or', 319),
        ('QC', 'Val-David', 320),
        ('QC', 'Val-des-Monts', 321),
        ('QC', 'Val-des-Sources', 322),
        ('QC', 'Val-Morin', 323),
        ('QC', 'Varennes', 324),
        ('QC', 'Vaudreuil-Dorion', 325),
        ('QC', 'Verchères', 326),
        ('QC', 'Victoriaville', 327),
        ('QC', 'Warwick', 328),
        ('QC', 'Waskaganish', 329),
        ('QC', 'Waterloo', 330),
        ('QC', 'Weedon', 331),
        ('QC', 'Westmount', 332),
        ('QC', 'Wickham', 333),
        ('QC', 'Windsor', 334),
        ('QC', 'Yamachiche', 335),
        ('QC', 'Other', 32767),
        ('ON', 'Addington Highlands', 1),
        ('ON', 'Adelaide-Metcalfe', 2),
        ('ON', 'Adjala-Tosorontio', 3),
        ('ON', 'Admaston/Bromley', 4),
        ('ON', 'Ajax', 5),
        ('ON', 'Alfred and Plantagenet', 6),
        ('ON', 'Algonquin Highlands', 7),
        ('ON', 'Alnwick/Haldimand', 8),
        ('ON', 'Amaranth', 9),
        ('ON', 'Amherstburg', 10),
        ('ON', 'Arnprior', 11),
        ('ON', 'Arran-Elderslie', 12),
        ('ON', 'Ashfield-Colborne-Wawanosh', 13),
        ('ON', 'Asphodel-Norwood', 14),
        ('ON', 'Athens', 15),
        ('ON', 'Atikokan', 16),
        ('ON', 'Augusta', 17),
        ('ON', 'Aurora', 18),
        ('ON', 'Aylmer', 19),
        ('ON', 'Bancroft', 20),
        ('ON', 'Barrie', 21),
        ('ON', 'Bayham', 22),
        ('ON', 'Beckwith', 23),
        ('ON', 'Belleville', 24),
        ('ON', 'Black River-Matheson', 25),
        ('ON', 'Blandford-Blenheim', 26),
        ('ON', 'Blind River', 27),
        ('ON', 'Bluewater', 28),
        ('ON', 'Bonnechere Valley', 29),
        ('ON', 'Bracebridge', 30),
        ('ON', 'Bradford West Gwillimbury', 31),
        ('ON', 'Brampton', 32),
        ('ON', 'Brant', 33),
        ('ON', 'Brantford', 34),
        ('ON', 'Brighton', 35),
        ('ON', 'Brock', 36),
        ('ON', 'Brockton', 37),
        ('ON', 'Brockville', 38),
        ('ON', 'Burlington', 39),
        ('ON', 'Caledon', 40),
        ('ON', 'Callander', 41),
        ('ON', 'Cambridge', 42),
        ('ON', 'Carleton Place', 43),
        ('ON', 'Casselman', 44),
        ('ON', 'Cavan Monaghan', 45),
        ('ON', 'Central Elgin', 46),
        ('ON', 'Central Frontenac', 47),
        ('ON', 'Central Huron', 48),
        ('ON', 'Centre Hastings', 49),
        ('ON', 'Centre Wellington', 50),
        ('ON', 'Champlain', 51),
        ('ON', 'Chatham-Kent', 52),
        ('ON', 'Chatsworth', 53),
        ('ON', 'Clarence-Rockland', 54),
        ('ON', 'Clarington', 55),
        ('ON', 'Clearview', 56),
        ('ON', 'Cobourg', 57),
        ('ON', 'Cochrane', 58),
        ('ON', 'Collingwood', 59),
        ('ON', 'Cornwall', 60),
        ('ON', 'Cramahe', 61),
        ('ON', 'Deep River', 62),
        ('ON', 'Douro-Dummer', 63),
        ('ON', 'Drummond/North Elmsley', 64),
        ('ON', 'Dryden', 65),
        ('ON', 'Dutton/Dunwich', 66),
        ('ON', 'Dysart et al', 67),
        ('ON', 'East Ferris', 68),
        ('ON', 'East Garafraxa', 69),
        ('ON', 'East Gwillimbury', 70),
        ('ON', 'East Hawkesbury', 71),
        ('ON', 'East Zorra-Tavistock', 72),
        ('ON', 'Edwardsburgh/Cardinal', 73),
        ('ON', 'Elizabethtown-Kitley', 74),
        ('ON', 'Elliot Lake', 75),
        ('ON', 'Enniskillen', 76),
        ('ON', 'Erin', 77),
        ('ON', 'Espanola', 78),
        ('ON', 'Essa', 79),
        ('ON', 'Essex', 80),
        ('ON', 'Fort Erie', 81),
        ('ON', 'Fort Frances', 82),
        ('ON', 'French River / Rivière des Français', 83),
        ('ON', 'Front of Yonge', 84),
        ('ON', 'Gananoque', 85),
        ('ON', 'Georgian Bay', 86),
        ('ON', 'Georgian Bluffs', 87),
        ('ON', 'Georgina', 88),
        ('ON', 'Goderich', 89),
        ('ON', 'Grand Valley', 90),
        ('ON', 'Gravenhurst', 91),
        ('ON', 'Greater Madawaska', 92),
        ('ON', 'Greater Napanee', 93),
        ('ON', 'Greater Sudbury / Grand Sudbury', 94),
        ('ON', 'Greenstone', 95),
        ('ON', 'Grey Highlands', 96),
        ('ON', 'Grimsby', 97),
        ('ON', 'Guelph', 98),
        ('ON', 'Guelph/Eramosa', 99),
        ('ON', 'Haldimand County', 100),
        ('ON', 'Halton Hills', 101),
        ('ON', 'Hamilton [SGC 3514019]', 102),
        ('ON', 'Hamilton [SGC 3525005]', 103),
        ('ON', 'Hanover', 104),
        ('ON', 'Hastings Highlands', 105),
        ('ON', 'Havelock-Belmont-Methuen', 106),
        ('ON', 'Hawkesbury', 107),
        ('ON', 'Hearst', 108),
        ('ON', 'Highlands East', 109),
        ('ON', 'Horton', 110),
        ('ON', 'Howick', 111),
        ('ON', 'Huntsville', 112),
        ('ON', 'Huron East', 113),
        ('ON', 'Huron-Kinloss', 114),
        ('ON', 'Ingersoll', 115),
        ('ON', 'Innisfil', 116),
        ('ON', 'Iroquois Falls', 117),
        ('ON', 'Kapuskasing', 118),
        ('ON', 'Kawartha Lakes', 119),
        ('ON', 'Kenora', 120),
        ('ON', 'Kincardine', 121),
        ('ON', 'King', 122),
        ('ON', 'Kingston', 123),
        ('ON', 'Kingsville', 124),
        ('ON', 'Kirkland Lake', 125),
        ('ON', 'Kitchener', 126),
        ('ON', 'Lake of Bays', 127),
        ('ON', 'Lakeshore', 128),
        ('ON', 'Lambton Shores', 129),
        ('ON', 'Lanark Highlands', 130),
        ('ON', 'LaSalle', 131),
        ('ON', 'Laurentian Hills', 132),
        ('ON', 'Laurentian Valley', 133),
        ('ON', 'Leamington', 134),
        ('ON', 'Leeds and the Thousand Islands', 135),
        ('ON', 'Lincoln', 136),
        ('ON', 'London', 137),
        ('ON', 'Loyalist', 138),
        ('ON', 'Lucan Biddulph', 139),
        ('ON', 'Madawaska Valley', 140),
        ('ON', 'Malahide', 141),
        ('ON', 'Mapleton', 142),
        ('ON', 'Marathon', 143),
        ('ON', 'Markham', 144),
        ('ON', 'Markstay-Warren', 145),
        ('ON', 'Marmora and Lake', 146),
        ('ON', 'McDougall', 147),
        ('ON', 'McNab/Braeside', 148),
        ('ON', 'Meaford', 149),
        ('ON', 'Melancthon', 150),
        ('ON', 'Merrickville-Wolford', 151),
        ('ON', 'Middlesex Centre', 152),
        ('ON', 'Midland', 153),
        ('ON', 'Milton', 154),
        ('ON', 'Minden Hills', 155),
        ('ON', 'Minto', 156),
        ('ON', 'Mississauga', 157),
        ('ON', 'Mississippi Mills', 158),
        ('ON', 'Mono', 159),
        ('ON', 'Montague', 160),
        ('ON', 'Morris-Turnberry', 161),
        ('ON', 'Mulmur', 162),
        ('ON', 'Muskoka Lakes', 163),
        ('ON', 'New Tecumseth', 164),
        ('ON', 'Newmarket', 165),
        ('ON', 'Niagara Falls', 166),
        ('ON', 'Niagara-on-the-Lake', 167),
        ('ON', 'Norfolk County', 168),
        ('ON', 'North Algona Wilberforce', 169),
        ('ON', 'North Bay', 170),
        ('ON', 'North Dumfries', 171),
        ('ON', 'North Dundas', 172),
        ('ON', 'North Glengarry', 173),
        ('ON', 'North Grenville', 174),
        ('ON', 'North Huron', 175),
        ('ON', 'North Kawartha', 176),
        ('ON', 'North Middlesex', 177),
        ('ON', 'North Perth', 178),
        ('ON', 'North Stormont', 179),
        ('ON', 'Northeastern Manitoulin and the Islands', 180),
        ('ON', 'Northern Bruce Peninsula', 181),
        ('ON', 'Norwich', 182),
        ('ON', 'Oakville', 183),
        ('ON', 'Oliver Paipoonge', 184),
        ('ON', 'Orangeville', 185),
        ('ON', 'Orillia', 186),
        ('ON', 'Oro-Medonte', 187),
        ('ON', 'Oshawa', 188),
        ('ON', 'Otonabee-South Monaghan', 189),
        ('ON', 'Ottawa', 190),
        ('ON', 'Owen Sound', 191),
        ('ON', 'Parry Sound', 192),
        ('ON', 'Pelham', 193),
        ('ON', 'Pembroke', 194),
        ('ON', 'Penetanguishene', 195),
        ('ON', 'Perry', 196),
        ('ON', 'Perth', 197),
        ('ON', 'Perth East', 198),
        ('ON', 'Perth South', 199),
        ('ON', 'Petawawa', 200),
        ('ON', 'Peterborough', 201),
        ('ON', 'Petrolia', 202),
        ('ON', 'Pickering', 203),
        ('ON', 'Plympton-Wyoming', 204),
        ('ON', 'Port Colborne', 205),
        ('ON', 'Port Hope', 206),
        ('ON', 'Powassan', 207),
        ('ON', 'Prescott', 208),
        ('ON', 'Prince Edward County', 209),
        ('ON', 'Puslinch', 210),
        ('ON', 'Quinte West', 211),
        ('ON', 'Ramara', 212),
        ('ON', 'Red Lake', 213),
        ('ON', 'Renfrew', 214),
        ('ON', 'Richmond Hill', 215),
        ('ON', 'Rideau Lakes', 216),
        ('ON', 'Russell', 217),
        ('ON', 'Sables-Spanish Rivers', 218),
        ('ON', 'Sarnia', 219),
        ('ON', 'Saugeen Shores', 220),
        ('ON', 'Sault Ste. Marie', 221),
        ('ON', 'Scugog', 222),
        ('ON', 'Seguin', 223),
        ('ON', 'Selwyn', 224),
        ('ON', 'Severn', 225),
        ('ON', 'Shelburne', 226),
        ('ON', 'Shuniah', 227),
        ('ON', 'Sioux Lookout', 228),
        ('ON', 'Smiths Falls', 229),
        ('ON', 'South Bruce', 230),
        ('ON', 'South Bruce Peninsula', 231),
        ('ON', 'South Dundas', 232),
        ('ON', 'South Frontenac', 233),
        ('ON', 'South Glengarry', 234),
        ('ON', 'South Huron', 235),
        ('ON', 'South Stormont', 236),
        ('ON', 'South-West Oxford', 237),
        ('ON', 'Southgate', 238),
        ('ON', 'Southwest Middlesex', 239),
        ('ON', 'Southwold', 240),
        ('ON', 'Springwater', 241),
        ('ON', 'St. Catharines', 242),
        ('ON', 'St. Clair', 243),
        ('ON', 'St. Marys', 244),
        ('ON', 'St. Thomas', 245),
        ('ON', 'Stirling-Rawdon', 246),
        ('ON', 'Stone Mills', 247),
        ('ON', 'Stratford', 248),
        ('ON', 'Strathroy-Caradoc', 249),
        ('ON', 'Tay', 250),
        ('ON', 'Tay Valley', 251),
        ('ON', 'Tecumseh', 252),
        ('ON', 'Temiskaming Shores', 253),
        ('ON', 'Thames Centre', 254),
        ('ON', 'The Blue Mountains', 255),
        ('ON', 'The Nation / La Nation', 256),
        ('ON', 'Thorold', 257),
        ('ON', 'Thunder Bay', 258),
        ('ON', 'Tillsonburg', 259),
        ('ON', 'Timmins', 260),
        ('ON', 'Tiny', 261),
        ('ON', 'Toronto', 262),
        ('ON', 'Trent Hills', 263),
        ('ON', 'Trent Lakes', 264),
        ('ON', 'Tweed', 265),
        ('ON', 'Tyendinaga', 266),
        ('ON', 'Tyendinaga Mohawk Territory', 267),
        ('ON', 'Uxbridge', 268),
        ('ON', 'Vaughan', 269),
        ('ON', 'Wainfleet', 270),
        ('ON', 'Warwick', 271),
        ('ON', 'Wasaga Beach', 272),
        ('ON', 'Waterloo', 273),
        ('ON', 'Wawa', 274),
        ('ON', 'Welland', 275),
        ('ON', 'Wellesley', 276),
        ('ON', 'Wellington North', 277),
        ('ON', 'West Elgin', 278),
        ('ON', 'West Grey', 279),
        ('ON', 'West Lincoln', 280),
        ('ON', 'West Nipissing / Nipissing Ouest', 281),
        ('ON', 'West Perth', 282),
        ('ON', 'Whitby', 283),
        ('ON', 'Whitchurch-Stouffville', 284),
        ('ON', 'Whitewater Region', 285),
        ('ON', 'Wikwemikong Unceded', 286),
        ('ON', 'Wilmot', 287),
        ('ON', 'Windsor', 288),
        ('ON', 'Woodstock', 289),
        ('ON', 'Woolwich', 290),
        ('ON', 'Zorra', 291),
        ('ON', 'Other', 32767),
        ('MB', 'Alexander', 1),
        ('MB', 'Altona', 2),
        ('MB', 'Beausejour', 3),
        ('MB', 'Bifrost-Riverton', 4),
        ('MB', 'Brandon', 5),
        ('MB', 'Brokenhead', 6),
        ('MB', 'Carman', 7),
        ('MB', 'Cartier', 8),
        ('MB', 'Cornwallis', 9),
        ('MB', 'Dauphin', 10),
        ('MB', 'De Salaberry', 11),
        ('MB', 'Dufferin', 12),
        ('MB', 'East St. Paul', 13),
        ('MB', 'Flin Flon (Part)', 14),
        ('MB', 'Garden Hill First Nation', 15),
        ('MB', 'Gimli', 16),
        ('MB', 'Grey', 17),
        ('MB', 'Hanover', 18),
        ('MB', 'Headingley', 19),
        ('MB', 'Hillsburg-Roblin-Shell River', 20),
        ('MB', 'Killarney - Turtle Mountain', 21),
        ('MB', 'La Broquerie', 22),
        ('MB', 'Lac du Bonnet', 23),
        ('MB', 'Lorne', 24),
        ('MB', 'Macdonald', 25),
        ('MB', 'Minnedosa', 26),
        ('MB', 'Morden', 27),
        ('MB', 'Morris', 28),
        ('MB', 'Neepawa', 29),
        ('MB', 'Niverville', 30),
        ('MB', 'North Cypress-Langford', 31),
        ('MB', 'North Norfolk', 32),
        ('MB', 'Norway House 17', 33),
        ('MB', 'Peguis 1B', 34),
        ('MB', 'Portage la Prairie [SGC 4609024]', 35),
        ('MB', 'Portage la Prairie [SGC 4609029]', 36),
        ('MB', 'Rhineland', 37),
        ('MB', 'Ritchot', 38),
        ('MB', 'Rockwood', 39),
        ('MB', 'Russell-Binscarth', 40),
        ('MB', 'Sandy Bay 5', 41),
        ('MB', 'Selkirk', 42),
        ('MB', 'Souris-Glenwood', 43),
        ('MB', 'Springfield', 44),
        ('MB', 'St. Andrews', 45),
        ('MB', 'St. Clements', 46),
        ('MB', 'St. Theresa Point', 47),
        ('MB', 'Stanley', 48),
        ('MB', 'Ste. Anne [SGC 4602057]', 49),
        ('MB', 'Ste. Anne [SGC 4602061]', 50),
        ('MB', 'Steinbach', 51),
        ('MB', 'Stonewall', 52),
        ('MB', 'Swan River', 53),
        ('MB', 'Swan Valley West', 54),
        ('MB', 'Taché', 55),
        ('MB', 'The Pas', 56),
        ('MB', 'Thompson', 57),
        ('MB', 'Virden', 58),
        ('MB', 'Wallace-Woodworth', 59),
        ('MB', 'West St. Paul', 60),
        ('MB', 'WestLake-Gladstone', 61),
        ('MB', 'Winkler', 62),
        ('MB', 'Winnipeg', 63),
        ('MB', 'Woodlands', 64),
        ('MB', 'Other', 32767),
        ('SK', 'Battleford', 1),
        ('SK', 'Buckland No. 491', 2),
        ('SK', 'Corman Park No. 344', 3),
        ('SK', 'Edenwold No. 158', 4),
        ('SK', 'Estevan', 5),
        ('SK', 'Humboldt', 6),
        ('SK', 'Kindersley', 7),
        ('SK', 'La Loche', 8),
        ('SK', 'La Ronge', 9),
        ('SK', 'Lloydminster (Part)', 10),
        ('SK', 'Martensville', 11),
        ('SK', 'Meadow Lake', 12),
        ('SK', 'Meadow Lake No. 588', 13),
        ('SK', 'Melfort', 14),
        ('SK', 'Melville', 15),
        ('SK', 'Moose Jaw', 16),
        ('SK', 'Moosomin', 17),
        ('SK', 'Nipawin', 18),
        ('SK', 'North Battleford', 19),
        ('SK', 'Pilot Butte', 20),
        ('SK', 'Prince Albert', 21),
        ('SK', 'Prince Albert No. 461', 22),
        ('SK', 'Regina', 23),
        ('SK', 'Rosetown', 24),
        ('SK', 'Saskatoon', 25),
        ('SK', 'Swift Current', 26),
        ('SK', 'Tisdale', 27),
        ('SK', 'Vanscoy No. 345', 28),
        ('SK', 'Warman', 29),
        ('SK', 'Weyburn', 30),
        ('SK', 'White City', 31),
        ('SK', 'Yorkton', 32),
        ('SK', 'Other', 32767),
        ('AB', 'Airdrie', 1),
        ('AB', 'Athabasca', 2),
        ('AB', 'Athabasca County', 3),
        ('AB', 'Banff', 4),
        ('AB', 'Barrhead', 5),
        ('AB', 'Barrhead County No. 11', 6),
        ('AB', 'Beaumont', 7),
        ('AB', 'Beaver County', 8),
        ('AB', 'Big Lakes County', 9),
        ('AB', 'Black Diamond', 10),
        ('AB', 'Blackfalds', 11),
        ('AB', 'Blood 148', 12),
        ('AB', 'Bonnyville', 13),
        ('AB', 'Bonnyville No. 87', 14),
        ('AB', 'Brazeau County', 15),
        ('AB', 'Brooks', 16),
        ('AB', 'Calgary', 17),
        ('AB', 'Camrose', 18),
        ('AB', 'Camrose County', 19),
        ('AB', 'Canmore', 20),
        ('AB', 'Cardston', 21),
        ('AB', 'Cardston County', 22),
        ('AB', 'Carstairs', 23),
        ('AB', 'Chestermere', 24),
        ('AB', 'Claresholm', 25),
        ('AB', 'Clear Hills', 26),
        ('AB', 'Clearwater County', 27),
        ('AB', 'Coaldale', 28),
        ('AB', 'Coalhurst', 29),
        ('AB', 'Cochrane', 30),
        ('AB', 'Cold Lake', 31),
        ('AB', 'Crossfield', 32),
        ('AB', 'Crowsnest Pass', 33),
        ('AB', 'Cypress County', 34),
        ('AB', 'Devon', 35),
        ('AB', 'Didsbury', 36),
        ('AB', 'Drayton Valley', 37),
        ('AB', 'Drumheller', 38),
        ('AB', 'Edmonton', 39),
        ('AB', 'Edson', 40),
        ('AB', 'Fairview', 41),
        ('AB', 'Flagstaff County', 42),
        ('AB', 'Foothills County', 43),
        ('AB', 'Fort Macleod', 44),
        ('AB', 'Fort Saskatchewan', 45),
        ('AB', 'Forty Mile County No. 8', 46),
        ('AB', 'Gibbons', 47),
        ('AB', 'Grande Prairie', 48),
        ('AB', 'Grande Prairie County No. 1', 49),
        ('AB', 'Greenview No. 16', 50),
        ('AB', 'Grimshaw', 51),
        ('AB', 'High Level', 52),
        ('AB', 'High River', 53),
        ('AB', 'Hinton', 54),
        ('AB', 'Innisfail', 55),
        ('AB', 'Jasper', 56),
        ('AB', 'Kneehill County', 57),
        ('AB', 'Lac la Biche County', 58),
        ('AB', 'Lac Ste. Anne County', 59),
        ('AB', 'Lacombe', 60),
        ('AB', 'Lacombe County', 61),
        ('AB', 'Lamont County', 62),
        ('AB', 'Leduc', 63),
        ('AB', 'Leduc County', 64),
        ('AB', 'Lesser Slave River No. 124', 65),
        ('AB', 'Lethbridge', 66),
        ('AB', 'Lethbridge County', 67),
        ('AB', 'Lloydminster (Part)', 68),
        ('AB', 'Mackenzie County', 69),
        ('AB', 'Medicine Hat', 70),
        ('AB', 'Minburn County No. 27', 71),
        ('AB', 'Morinville', 72),
        ('AB', 'Mountain View County', 73),
        ('AB', 'Newell County', 74),
        ('AB', 'Northern Lights County', 75),
        ('AB', 'Okotoks', 76),
        ('AB', 'Olds', 77),
        ('AB', 'Opportunity No. 17', 78),
        ('AB', 'Parkland County', 79),
        ('AB', 'Peace River', 80),
        ('AB', 'Penhold', 81),
        ('AB', 'Pincher Creek', 82),
        ('AB', 'Pincher Creek No. 9', 83),
        ('AB', 'Ponoka', 84),
        ('AB', 'Ponoka County', 85),
        ('AB', 'Raymond', 86),
        ('AB', 'Red Deer', 87),
        ('AB', 'Red Deer County', 88),
        ('AB', 'Redcliff', 89),
        ('AB', 'Rocky Mountain House', 90),
        ('AB', 'Rocky View County', 91),
        ('AB', 'Samson 137', 92),
        ('AB', 'Siksika 146', 93),
        ('AB', 'Slave Lake', 94),
        ('AB', 'Smoky Lake County', 95),
        ('AB', 'Spruce Grove', 96),
        ('AB', 'St. Albert', 97),
        ('AB', 'St. Paul', 98),
        ('AB', 'St. Paul County No. 19', 99),
        ('AB', 'Stettler', 100),
        ('AB', 'Stettler County No. 6', 101),
        ('AB', 'Stony Plain', 102),
        ('AB', 'Strathcona County', 103),
        ('AB', 'Strathmore', 104),
        ('AB', 'Sturgeon County', 105),
        ('AB', 'Sundre', 106),
        ('AB', 'Sylvan Lake', 107),
        ('AB', 'Taber [SGC 4802021]', 108),
        ('AB', 'Taber [SGC 4802022]', 109),
        ('AB', 'Thorhild County', 110),
        ('AB', 'Three Hills', 111),
        ('AB', 'Turner Valley', 112),
        ('AB', 'Two Hills County No. 21', 113),
        ('AB', 'Vegreville', 114),
        ('AB', 'Vermilion', 115),
        ('AB', 'Vermilion River County', 116),
        ('AB', 'Vulcan County', 117),
        ('AB', 'Wainwright', 118),
        ('AB', 'Wainwright No. 61', 119),
        ('AB', 'Warner County No. 5', 120),
        ('AB', 'Westlock', 121),
        ('AB', 'Westlock County', 122),
        ('AB', 'Wetaskiwin', 123),
        ('AB', 'Wetaskiwin County No. 10', 124),
        ('AB', 'Wheatland County', 125),
        ('AB', 'Whitecourt', 126),
        ('AB', 'Willow Creek No. 26', 127),
        ('AB', 'Wood Buffalo', 128),
        ('AB', 'Woodlands County', 129),
        ('AB', 'Yellowhead County', 130),
        ('AB', 'Other', 32767),
        ('BC', 'Abbotsford', 1),
        ('BC', 'Armstrong', 2),
        ('BC', 'Bowen Island', 3),
        ('BC', 'Burnaby', 4),
        ('BC', 'Campbell River', 5),
        ('BC', 'Capilano 5', 6),
        ('BC', 'Castlegar', 7),
        ('BC', 'Central Saanich', 8),
        ('BC', 'Chilliwack', 9),
        ('BC', 'Coldstream', 10),
        ('BC', 'Colwood', 11),
        ('BC', 'Comox', 12),
        ('BC', 'Coquitlam', 13),
        ('BC', 'Courtenay', 14),
        ('BC', 'Cranbrook', 15),
        ('BC', 'Creston', 16),
        ('BC', 'Cumberland', 17),
        ('BC', 'Dawson Creek', 18),
        ('BC', 'Delta', 19),
        ('BC', 'Duncan', 20),
        ('BC', 'Elkford', 21),
        ('BC', 'Enderby', 22),
        ('BC', 'Esquimalt', 23),
        ('BC', 'Fernie', 24),
        ('BC', 'Fort St. John', 25),
        ('BC', 'Gibsons', 26),
        ('BC', 'Golden', 27),
        ('BC', 'Grand Forks', 28),
        ('BC', 'Hope', 29),
        ('BC', 'Houston', 30),
        ('BC', 'Invermere', 31),
        ('BC', 'Kamloops', 32),
        ('BC', 'Kamloops 1', 33),
        ('BC', 'Kelowna', 34),
        ('BC', 'Kent', 35),
        ('BC', 'Kimberley', 36),
        ('BC', 'Kitimat', 37),
        ('BC', 'Ladysmith', 38),
        ('BC', 'Lake Country', 39),
        ('BC', 'Lake Cowichan', 40),
        ('BC', 'Langford', 41),
        ('BC', 'Langley [SGC 5915001]', 42),
        ('BC', 'Langley [SGC 5915002]', 43),
        ('BC', 'Lantzville', 44),
        ('BC', 'Mackenzie', 45),
        ('BC', 'Maple Ridge', 46),
        ('BC', 'Merritt', 47),
        ('BC', 'Metchosin', 48),
        ('BC', 'Mission', 49),
        ('BC', 'Nanaimo', 50),
        ('BC', 'Nelson', 51),
        ('BC', 'New Westminster', 52),
        ('BC', 'North Cowichan', 53),
        ('BC', 'North Saanich', 54),
        ('BC', 'North Vancouver [SGC 5915046]', 55),
        ('BC', 'North Vancouver [SGC 5915051]', 56),
        ('BC', 'Northern Rockies', 57),
        ('BC', 'Oak Bay', 58),
        ('BC', 'Okanagan (Part) 1', 59),
        ('BC', 'Oliver', 60),
        ('BC', 'Osoyoos', 61),
        ('BC', 'Parksville', 62),
        ('BC', 'Peachland', 63),
        ('BC', 'Pemberton', 64),
        ('BC', 'Penticton', 65),
        ('BC', 'Pitt Meadows', 66),
        ('BC', 'Port Alberni', 67),
        ('BC', 'Port Coquitlam', 68),
        ('BC', 'Port Hardy', 69),
        ('BC', 'Port Moody', 70),
        ('BC', 'Powell River', 71),
        ('BC', 'Prince George', 72),
        ('BC', 'Prince Rupert', 73),
        ('BC', 'Princeton', 74),
        ('BC', 'Qualicum Beach', 75),
        ('BC', 'Quesnel', 76),
        ('BC', 'Revelstoke', 77),
        ('BC', 'Richmond', 78),
        ('BC', 'Rossland', 79),
        ('BC', 'Saanich', 80),
        ('BC', 'Salmon Arm', 81),
        ('BC', 'Sechelt', 82),
        ('BC', 'Sicamous', 83),
        ('BC', 'Sidney', 84),
        ('BC', 'Smithers', 85),
        ('BC', 'Sooke', 86),
        ('BC', 'Spallumcheen', 87),
        ('BC', 'Sparwood', 88),
        ('BC', 'Squamish', 89),
        ('BC', 'Summerland', 90),
        ('BC', 'Surrey', 91),
        ('BC', 'Terrace', 92),
        ('BC', 'Tofino', 93),
        ('BC', 'Trail', 94),
        ('BC', 'Tsinstikeptum 9', 95),
        ('BC', 'Tzeachten 13', 96),
        ('BC', 'Vancouver', 97),
        ('BC', 'Vanderhoof', 98),
        ('BC', 'Vernon', 99),
        ('BC', 'Victoria', 100),
        ('BC', 'View Royal', 101),
        ('BC', 'West Kelowna', 102),
        ('BC', 'West Vancouver', 103),
        ('BC', 'Whistler', 104),
        ('BC', 'White Rock', 105),
        ('BC', 'Williams Lake', 106),
        ('BC', 'Other', 32767),
        ('YT', 'Whitehorse', 1),
        ('YT', 'Other', 32767),
        ('NT', 'Hay River', 1),
        ('NT', 'Inuvik', 2),
        ('NT', 'Yellowknife', 3),
        ('NT', 'Other', 32767),
        ('NU', 'Arviat', 1),
        ('NU', 'Iqaluit', 2),
        ('NU', 'Rankin Inlet', 3),
        ('NU', 'Other', 32767)
) AS city_data (state_code, name, display_order)
INNER JOIN master_countries country
    ON country.iso_code = 'CA'
INNER JOIN master_states state
    ON state.country_id = country.id
   AND state.code = city_data.state_code
ON CONFLICT (state_id, name) DO UPDATE
SET display_order = EXCLUDED.display_order,
    is_active = TRUE,
    updated_at = CURRENT_TIMESTAMP;

COMMIT;