-- India State/UT and district seed data
-- Source basis: Government of India state/district directory and LGD district export.
-- IMPORTANT: master_cities rows below represent DISTRICTS because the requested IGOD page is a district directory.
-- Change v_country_id below if India has a different ID in master_countries.

BEGIN;

TRUNCATE TABLE master_states RESTART IDENTITY;

TRUNCATE TABLE master_cities RESTART IDENTITY;

DO $$
DECLARE
    v_country_id SMALLINT := 1;
BEGIN
    INSERT INTO master_states (
        country_id, code, name, display_order, is_active, created_at, updated_at
    )
    VALUES
        (v_country_id, 'AN', 'Andaman and Nicobar Islands', 1, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'AP', 'Andhra Pradesh', 2, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'AR', 'Arunachal Pradesh', 3, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'AS', 'Assam', 4, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'BR', 'Bihar', 5, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'CH', 'Chandigarh', 6, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'CG', 'Chhattisgarh', 7, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'DN', 'Dadra and Nagar Haveli and Daman and Diu', 8, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'DL', 'Delhi', 9, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'GA', 'Goa', 10, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'GJ', 'Gujarat', 11, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'HR', 'Haryana', 12, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'HP', 'Himachal Pradesh', 13, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'JK', 'Jammu and Kashmir', 14, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'JH', 'Jharkhand', 15, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'KA', 'Karnataka', 16, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'KL', 'Kerala', 17, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'LA', 'Ladakh', 18, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'LD', 'Lakshadweep', 19, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'MP', 'Madhya Pradesh', 20, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'MH', 'Maharashtra', 21, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'MN', 'Manipur', 22, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'ML', 'Meghalaya', 23, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'MZ', 'Mizoram', 24, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'NL', 'Nagaland', 25, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'OD', 'Odisha', 26, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'PY', 'Puducherry', 27, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'PB', 'Punjab', 28, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'RJ', 'Rajasthan', 29, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'SK', 'Sikkim', 30, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'TN', 'Tamil Nadu', 31, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'TS', 'Telangana', 32, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'TR', 'Tripura', 33, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'UP', 'Uttar Pradesh', 34, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'UK', 'Uttarakhand', 35, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        (v_country_id, 'WB', 'West Bengal', 36, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    ON CONFLICT (country_id, code) DO UPDATE
    SET name = EXCLUDED.name,
        display_order = EXCLUDED.display_order,
        is_active = EXCLUDED.is_active,
        updated_at = CURRENT_TIMESTAMP;

    INSERT INTO master_cities (
        state_id, name, display_order, is_active, created_at, updated_at
    )
    SELECT
        ms.id,
        d.district_name,
        d.display_order,
        TRUE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    FROM (VALUES
        ('AN', 'Nicobars', 1),
        ('AN', 'North And Middle Andaman', 2),
        ('AN', 'South Andamans', 3),
        ('AP', 'Alluri Sitharama Raju', 1),
        ('AP', 'Anakapalli', 2),
        ('AP', 'Anantapur', 3),
        ('AP', 'Annamayya', 4),
        ('AP', 'Bapatla', 5),
        ('AP', 'Chittoor', 6),
        ('AP', 'East Godavari', 7),
        ('AP', 'Eluru', 8),
        ('AP', 'Guntur', 9),
        ('AP', 'Kakinada', 10),
        ('AP', 'Konaseema', 11),
        ('AP', 'Krishna', 12),
        ('AP', 'Kurnool', 13),
        ('AP', 'Nandyal', 14),
        ('AP', 'NTR', 15),
        ('AP', 'Palnadu', 16),
        ('AP', 'Parvathipuram Manyam', 17),
        ('AP', 'Prakasam', 18),
        ('AP', 'SPSR Nellore', 19),
        ('AP', 'Sri Sathya Sai', 20),
        ('AP', 'Srikakulam', 21),
        ('AP', 'Tirupati', 22),
        ('AP', 'Visakhapatanam', 23),
        ('AP', 'Vizianagaram', 24),
        ('AP', 'West Godavari', 25),
        ('AP', 'Y.S.R.', 26),
        ('AR', 'Anjaw', 1),
        ('AR', 'Changlang', 2),
        ('AR', 'Dibang Valley', 3),
        ('AR', 'East Kameng', 4),
        ('AR', 'East Siang', 5),
        ('AR', 'Kamle', 6),
        ('AR', 'Kra Daadi', 7),
        ('AR', 'Kurung Kumey', 8),
        ('AR', 'Leparada', 9),
        ('AR', 'Lohit', 10),
        ('AR', 'Longding', 11),
        ('AR', 'Lower Dibang Valley', 12),
        ('AR', 'Lower Siang', 13),
        ('AR', 'Lower Subansiri', 14),
        ('AR', 'Namsai', 15),
        ('AR', 'Pakke Kessang', 16),
        ('AR', 'Papum Pare', 17),
        ('AR', 'Shi Yomi', 18),
        ('AR', 'Siang', 19),
        ('AR', 'Tawang', 20),
        ('AR', 'Tirap', 21),
        ('AR', 'Upper Siang', 22),
        ('AR', 'Upper Subansiri', 23),
        ('AR', 'West Kameng', 24),
        ('AR', 'West Siang', 25),
        ('AS', 'Bajali', 1),
        ('AS', 'Baksa', 2),
        ('AS', 'Barpeta', 3),
        ('AS', 'Biswanath', 4),
        ('AS', 'Bongaigaon', 5),
        ('AS', 'Cachar', 6),
        ('AS', 'Charaideo', 7),
        ('AS', 'Chirang', 8),
        ('AS', 'Darrang', 9),
        ('AS', 'Dhemaji', 10),
        ('AS', 'Dhubri', 11),
        ('AS', 'Dibrugarh', 12),
        ('AS', 'Dima Hasao', 13),
        ('AS', 'Goalpara', 14),
        ('AS', 'Golaghat', 15),
        ('AS', 'Hailakandi', 16),
        ('AS', 'Hojai', 17),
        ('AS', 'Jorhat', 18),
        ('AS', 'Kamrup', 19),
        ('AS', 'Kamrup Metro', 20),
        ('AS', 'Karbi Anglong', 21),
        ('AS', 'Karimganj', 22),
        ('AS', 'Kokrajhar', 23),
        ('AS', 'Lakhimpur', 24),
        ('AS', 'Majuli', 25),
        ('AS', 'Marigaon', 26),
        ('AS', 'Nagaon', 27),
        ('AS', 'Nalbari', 28),
        ('AS', 'Sivasagar', 29),
        ('AS', 'Sonitpur', 30),
        ('AS', 'South Salmara Mancachar', 31),
        ('AS', 'Tamulpur', 32),
        ('AS', 'Tinsukia', 33),
        ('AS', 'Udalguri', 34),
        ('AS', 'West Karbi Anglong', 35),
        ('BR', 'Araria', 1),
        ('BR', 'Arwal', 2),
        ('BR', 'Aurangabad', 3),
        ('BR', 'Banka', 4),
        ('BR', 'Begusarai', 5),
        ('BR', 'Bhagalpur', 6),
        ('BR', 'Bhojpur', 7),
        ('BR', 'Buxar', 8),
        ('BR', 'Darbhanga', 9),
        ('BR', 'Gaya', 10),
        ('BR', 'Gopalganj', 11),
        ('BR', 'Jamui', 12),
        ('BR', 'Jehanabad', 13),
        ('BR', 'Kaimur (Bhabua)', 14),
        ('BR', 'Katihar', 15),
        ('BR', 'Khagaria', 16),
        ('BR', 'Kishanganj', 17),
        ('BR', 'Lakhisarai', 18),
        ('BR', 'Madhepura', 19),
        ('BR', 'Madhubani', 20),
        ('BR', 'Munger', 21),
        ('BR', 'Muzaffarpur', 22),
        ('BR', 'Nalanda', 23),
        ('BR', 'Nawada', 24),
        ('BR', 'Pashchim Champaran', 25),
        ('BR', 'Patna', 26),
        ('BR', 'Purbi Champaran', 27),
        ('BR', 'Purnia', 28),
        ('BR', 'Rohtas', 29),
        ('BR', 'Saharsa', 30),
        ('BR', 'Samastipur', 31),
        ('BR', 'Saran', 32),
        ('BR', 'Sheikhpura', 33),
        ('BR', 'Sheohar', 34),
        ('BR', 'Sitamarhi', 35),
        ('BR', 'Siwan', 36),
        ('BR', 'Supaul', 37),
        ('BR', 'Vaishali', 38),
        ('CH', 'Chandigarh', 1),
        ('CG', 'Balod', 1),
        ('CG', 'Baloda Bazar', 2),
        ('CG', 'Balrampur', 3),
        ('CG', 'Bastar', 4),
        ('CG', 'Bemetara', 5),
        ('CG', 'Bijapur', 6),
        ('CG', 'Bilaspur', 7),
        ('CG', 'Dantewada', 8),
        ('CG', 'Dhamtari', 9),
        ('CG', 'Durg', 10),
        ('CG', 'Gariyaband', 11),
        ('CG', 'Gaurella Pendra Marwahi', 12),
        ('CG', 'Janjgir-Champa', 13),
        ('CG', 'Jashpur', 14),
        ('CG', 'Kabirdham', 15),
        ('CG', 'Kanker', 16),
        ('CG', 'Khairgarh Chhuikhadan Gandai', 17),
        ('CG', 'Kondagaon', 18),
        ('CG', 'Korba', 19),
        ('CG', 'Korea', 20),
        ('CG', 'Mahasamund', 21),
        ('CG', 'Manendragarh Chirimiri Bharatpur', 22),
        ('CG', 'Mohla Manpur Ambagarh Chouki', 23),
        ('CG', 'Mungeli', 24),
        ('CG', 'Narayanpur', 25),
        ('CG', 'Raigarh', 26),
        ('CG', 'Raipur', 27),
        ('CG', 'Rajnandgaon', 28),
        ('CG', 'Sakti', 29),
        ('CG', 'Sarangarh Bilaigarh', 30),
        ('CG', 'Sukma', 31),
        ('CG', 'Surajpur', 32),
        ('CG', 'Surguja', 33),
        ('DN', 'Dadra And Nagar Haveli', 1),
        ('DN', 'Daman', 2),
        ('DN', 'Diu', 3),
        ('DL', 'Central', 1),
        ('DL', 'East', 2),
        ('DL', 'New Delhi', 3),
        ('DL', 'North', 4),
        ('DL', 'North East', 5),
        ('DL', 'North West', 6),
        ('DL', 'Shahdara', 7),
        ('DL', 'South', 8),
        ('DL', 'South East', 9),
        ('DL', 'South West', 10),
        ('DL', 'West', 11),
        ('GA', 'North Goa', 1),
        ('GA', 'South Goa', 2),
        ('GJ', 'Ahmadabad', 1),
        ('GJ', 'Amreli', 2),
        ('GJ', 'Anand', 3),
        ('GJ', 'Arvalli', 4),
        ('GJ', 'Banas Kantha', 5),
        ('GJ', 'Bharuch', 6),
        ('GJ', 'Bhavnagar', 7),
        ('GJ', 'Botad', 8),
        ('GJ', 'Chhotaudepur', 9),
        ('GJ', 'Dang', 10),
        ('GJ', 'Devbhumi Dwarka', 11),
        ('GJ', 'Dohad', 12),
        ('GJ', 'Gandhinagar', 13),
        ('GJ', 'Gir Somnath', 14),
        ('GJ', 'Jamnagar', 15),
        ('GJ', 'Junagadh', 16),
        ('GJ', 'Kachchh', 17),
        ('GJ', 'Kheda', 18),
        ('GJ', 'Mahesana', 19),
        ('GJ', 'Mahisagar', 20),
        ('GJ', 'Morbi', 21),
        ('GJ', 'Narmada', 22),
        ('GJ', 'Navsari', 23),
        ('GJ', 'Panch Mahals', 24),
        ('GJ', 'Patan', 25),
        ('GJ', 'Porbandar', 26),
        ('GJ', 'Rajkot', 27),
        ('GJ', 'Sabar Kantha', 28),
        ('GJ', 'Surat', 29),
        ('GJ', 'Surendranagar', 30),
        ('GJ', 'Tapi', 31),
        ('GJ', 'Vadodara', 32),
        ('GJ', 'Valsad', 33),
        ('HR', 'Ambala', 1),
        ('HR', 'Bhiwani', 2),
        ('HR', 'Charki Dadri', 3),
        ('HR', 'Faridabad', 4),
        ('HR', 'Fatehabad', 5),
        ('HR', 'Gurugram', 6),
        ('HR', 'Hisar', 7),
        ('HR', 'Jhajjar', 8),
        ('HR', 'Jind', 9),
        ('HR', 'Kaithal', 10),
        ('HR', 'Karnal', 11),
        ('HR', 'Kurukshetra', 12),
        ('HR', 'Mahendragarh', 13),
        ('HR', 'Nuh', 14),
        ('HR', 'Palwal', 15),
        ('HR', 'Panchkula', 16),
        ('HR', 'Panipat', 17),
        ('HR', 'Rewari', 18),
        ('HR', 'Rohtak', 19),
        ('HR', 'Sirsa', 20),
        ('HR', 'Sonipat', 21),
        ('HR', 'Yamunanagar', 22),
        ('HP', 'Bilaspur', 1),
        ('HP', 'Chamba', 2),
        ('HP', 'Hamirpur', 3),
        ('HP', 'Kangra', 4),
        ('HP', 'Kinnaur', 5),
        ('HP', 'Kullu', 6),
        ('HP', 'Lahul And Spiti', 7),
        ('HP', 'Mandi', 8),
        ('HP', 'Shimla', 9),
        ('HP', 'Sirmaur', 10),
        ('HP', 'Solan', 11),
        ('HP', 'Una', 12),
        ('JK', 'Anantnag', 1),
        ('JK', 'Bandipora', 2),
        ('JK', 'Baramulla', 3),
        ('JK', 'Budgam', 4),
        ('JK', 'Doda', 5),
        ('JK', 'Ganderbal', 6),
        ('JK', 'Jammu', 7),
        ('JK', 'Kathua', 8),
        ('JK', 'Kishtwar', 9),
        ('JK', 'Kulgam', 10),
        ('JK', 'Kupwara', 11),
        ('JK', 'Poonch', 12),
        ('JK', 'Pulwama', 13),
        ('JK', 'Rajouri', 14),
        ('JK', 'Ramban', 15),
        ('JK', 'Reasi', 16),
        ('JK', 'Samba', 17),
        ('JK', 'Shopian', 18),
        ('JK', 'Srinagar', 19),
        ('JK', 'Udhampur', 20),
        ('JH', 'Bokaro', 1),
        ('JH', 'Chatra', 2),
        ('JH', 'Deoghar', 3),
        ('JH', 'Dhanbad', 4),
        ('JH', 'Dumka', 5),
        ('JH', 'East Singhbum', 6),
        ('JH', 'Garhwa', 7),
        ('JH', 'Giridih', 8),
        ('JH', 'Godda', 9),
        ('JH', 'Gumla', 10),
        ('JH', 'Hazaribagh', 11),
        ('JH', 'Jamtara', 12),
        ('JH', 'Khunti', 13),
        ('JH', 'Koderma', 14),
        ('JH', 'Latehar', 15),
        ('JH', 'Lohardaga', 16),
        ('JH', 'Pakur', 17),
        ('JH', 'Palamu', 18),
        ('JH', 'Ramgarh', 19),
        ('JH', 'Ranchi', 20),
        ('JH', 'Sahebganj', 21),
        ('JH', 'Saraikela Kharsawan', 22),
        ('JH', 'Simdega', 23),
        ('JH', 'West Singhbhum', 24),
        ('KA', 'Bagalkote', 1),
        ('KA', 'Ballari', 2),
        ('KA', 'Belagavi', 3),
        ('KA', 'Bengaluru Rural', 4),
        ('KA', 'Bengaluru Urban', 5),
        ('KA', 'Bidar', 6),
        ('KA', 'Chamarajanagara', 7),
        ('KA', 'Chikkaballapura', 8),
        ('KA', 'Chikkamagaluru', 9),
        ('KA', 'Chitradurga', 10),
        ('KA', 'Dakshina Kannada', 11),
        ('KA', 'Davangere', 12),
        ('KA', 'Dharwad', 13),
        ('KA', 'Gadag', 14),
        ('KA', 'Hassan', 15),
        ('KA', 'Haveri', 16),
        ('KA', 'Kalaburagi', 17),
        ('KA', 'Kodagu', 18),
        ('KA', 'Kolar', 19),
        ('KA', 'Koppal', 20),
        ('KA', 'Mandya', 21),
        ('KA', 'Mysuru', 22),
        ('KA', 'Raichur', 23),
        ('KA', 'Ramanagara', 24),
        ('KA', 'Shivamogga', 25),
        ('KA', 'Tumakuru', 26),
        ('KA', 'Udupi', 27),
        ('KA', 'Uttara Kannada', 28),
        ('KA', 'Vijayanagar', 29),
        ('KA', 'Vijayapura', 30),
        ('KA', 'Yadgir', 31),
        ('KL', 'Alappuzha', 1),
        ('KL', 'Ernakulam', 2),
        ('KL', 'Idukki', 3),
        ('KL', 'Kannur', 4),
        ('KL', 'Kasaragod', 5),
        ('KL', 'Kollam', 6),
        ('KL', 'Kottayam', 7),
        ('KL', 'Kozhikode', 8),
        ('KL', 'Malappuram', 9),
        ('KL', 'Palakkad', 10),
        ('KL', 'Pathanamthitta', 11),
        ('KL', 'Thiruvananthapuram', 12),
        ('KL', 'Thrissur', 13),
        ('KL', 'Wayanad', 14),
        ('LA', 'Kargil', 1),
        ('LA', 'Leh Ladakh', 2),
        ('LD', 'Lakshadweep District', 1),
        ('MP', 'Agar Malwa', 1),
        ('MP', 'Alirajpur', 2),
        ('MP', 'Anuppur', 3),
        ('MP', 'Ashoknagar', 4),
        ('MP', 'Balaghat', 5),
        ('MP', 'Barwani', 6),
        ('MP', 'Betul', 7),
        ('MP', 'Bhind', 8),
        ('MP', 'Bhopal', 9),
        ('MP', 'Burhanpur', 10),
        ('MP', 'Chhatarpur', 11),
        ('MP', 'Chhindwara', 12),
        ('MP', 'Damoh', 13),
        ('MP', 'Datia', 14),
        ('MP', 'Dewas', 15),
        ('MP', 'Dhar', 16),
        ('MP', 'Dindori', 17),
        ('MP', 'East Nimar', 18),
        ('MP', 'Guna', 19),
        ('MP', 'Gwalior', 20),
        ('MP', 'Harda', 21),
        ('MP', 'Indore', 22),
        ('MP', 'Jabalpur', 23),
        ('MP', 'Jhabua', 24),
        ('MP', 'Katni', 25),
        ('MP', 'Khargone', 26),
        ('MP', 'Mandla', 27),
        ('MP', 'Mandsaur', 28),
        ('MP', 'Morena', 29),
        ('MP', 'Narmadapuram', 30),
        ('MP', 'Narsinghpur', 31),
        ('MP', 'Neemuch', 32),
        ('MP', 'Niwari', 33),
        ('MP', 'Panna', 34),
        ('MP', 'Raisen', 35),
        ('MP', 'Rajgarh', 36),
        ('MP', 'Ratlam', 37),
        ('MP', 'Rewa', 38),
        ('MP', 'Sagar', 39),
        ('MP', 'Satna', 40),
        ('MP', 'Sehore', 41),
        ('MP', 'Seoni', 42),
        ('MP', 'Shahdol', 43),
        ('MP', 'Shajapur', 44),
        ('MP', 'Sheopur', 45),
        ('MP', 'Shivpuri', 46),
        ('MP', 'Sidhi', 47),
        ('MP', 'Singrauli', 48),
        ('MP', 'Tikamgarh', 49),
        ('MP', 'Ujjain', 50),
        ('MP', 'Umaria', 51),
        ('MP', 'Vidisha', 52),
        ('MH', 'Ahmednagar', 1),
        ('MH', 'Akola', 2),
        ('MH', 'Amravati', 3),
        ('MH', 'Aurangabad', 4),
        ('MH', 'Beed', 5),
        ('MH', 'Bhandara', 6),
        ('MH', 'Buldhana', 7),
        ('MH', 'Chandrapur', 8),
        ('MH', 'Dhule', 9),
        ('MH', 'Gadchiroli', 10),
        ('MH', 'Gondia', 11),
        ('MH', 'Hingoli', 12),
        ('MH', 'Jalgaon', 13),
        ('MH', 'Jalna', 14),
        ('MH', 'Kolhapur', 15),
        ('MH', 'Latur', 16),
        ('MH', 'Mumbai', 17),
        ('MH', 'Mumbai Suburban', 18),
        ('MH', 'Nagpur', 19),
        ('MH', 'Nanded', 20),
        ('MH', 'Nandurbar', 21),
        ('MH', 'Nashik', 22),
        ('MH', 'Osmanabad', 23),
        ('MH', 'Palghar', 24),
        ('MH', 'Parbhani', 25),
        ('MH', 'Pune', 26),
        ('MH', 'Raigad', 27),
        ('MH', 'Ratnagiri', 28),
        ('MH', 'Sangli', 29),
        ('MH', 'Satara', 30),
        ('MH', 'Sindhudurg', 31),
        ('MH', 'Solapur', 32),
        ('MH', 'Thane', 33),
        ('MH', 'Wardha', 34),
        ('MH', 'Washim', 35),
        ('MH', 'Yavatmal', 36),
        ('MN', 'Bishnupur', 1),
        ('MN', 'Chandel', 2),
        ('MN', 'Churachandpur', 3),
        ('MN', 'Imphal East', 4),
        ('MN', 'Imphal West', 5),
        ('MN', 'Jiribam', 6),
        ('MN', 'Kakching', 7),
        ('MN', 'Kamjong', 8),
        ('MN', 'Kangpokpi', 9),
        ('MN', 'Noney', 10),
        ('MN', 'Pherzawl', 11),
        ('MN', 'Senapati', 12),
        ('MN', 'Tamenglong', 13),
        ('MN', 'Tengnoupal', 14),
        ('MN', 'Thoubal', 15),
        ('MN', 'Ukhrul', 16),
        ('ML', 'East Garo Hills', 1),
        ('ML', 'East Jaintia Hills', 2),
        ('ML', 'East Khasi Hills', 3),
        ('ML', 'Eastern West Khasi Hills', 4),
        ('ML', 'North Garo Hills', 5),
        ('ML', 'Ri Bhoi', 6),
        ('ML', 'South Garo Hills', 7),
        ('ML', 'South West Garo Hills', 8),
        ('ML', 'South West Khasi Hills', 9),
        ('ML', 'West Garo Hills', 10),
        ('ML', 'West Jaintia Hills', 11),
        ('ML', 'West Khasi Hills', 12),
        ('MZ', 'Aizawl', 1),
        ('MZ', 'Champhai', 2),
        ('MZ', 'Hnahthial', 3),
        ('MZ', 'Khawzawl', 4),
        ('MZ', 'Kolasib', 5),
        ('MZ', 'Lawngtlai', 6),
        ('MZ', 'Lunglei', 7),
        ('MZ', 'Mamit', 8),
        ('MZ', 'Saiha', 9),
        ('MZ', 'Saitual', 10),
        ('MZ', 'Serchhip', 11),
        ('NL', 'Chumoukedima', 1),
        ('NL', 'Dimapur', 2),
        ('NL', 'Kiphire', 3),
        ('NL', 'Kohima', 4),
        ('NL', 'Longleng', 5),
        ('NL', 'Mokokchung', 6),
        ('NL', 'Mon', 7),
        ('NL', 'Noklak', 8),
        ('NL', 'Peren', 9),
        ('NL', 'Phek', 10),
        ('NL', 'Tseminyu', 11),
        ('NL', 'Tuensang', 12),
        ('NL', 'Wokha', 13),
        ('NL', 'Zunheboto', 14),
        ('OD', 'Anugul', 1),
        ('OD', 'Balangir', 2),
        ('OD', 'Baleshwar', 3),
        ('OD', 'Bargarh', 4),
        ('OD', 'Bhadrak', 5),
        ('OD', 'Boudh', 6),
        ('OD', 'Cuttack', 7),
        ('OD', 'Deogarh', 8),
        ('OD', 'Dhenkanal', 9),
        ('OD', 'Gajapati', 10),
        ('OD', 'Ganjam', 11),
        ('OD', 'Jagatsinghapur', 12),
        ('OD', 'Jajapur', 13),
        ('OD', 'Jharsuguda', 14),
        ('OD', 'Kalahandi', 15),
        ('OD', 'Kandhamal', 16),
        ('OD', 'Kendrapara', 17),
        ('OD', 'Kendujhar', 18),
        ('OD', 'Khordha', 19),
        ('OD', 'Koraput', 20),
        ('OD', 'Malkangiri', 21),
        ('OD', 'Mayurbhanj', 22),
        ('OD', 'Nabarangpur', 23),
        ('OD', 'Nayagarh', 24),
        ('OD', 'Nuapada', 25),
        ('OD', 'Puri', 26),
        ('OD', 'Rayagada', 27),
        ('OD', 'Sambalpur', 28),
        ('OD', 'Sonepur', 29),
        ('OD', 'Sundargarh', 30),
        ('PY', 'Karaikal', 1),
        ('PY', 'Mahe', 2),
        ('PY', 'Pondicherry', 3),
        ('PY', 'Yanam', 4),
        ('PB', 'Amritsar', 1),
        ('PB', 'Barnala', 2),
        ('PB', 'Bathinda', 3),
        ('PB', 'Faridkot', 4),
        ('PB', 'Fatehgarh Sahib', 5),
        ('PB', 'Fazilka', 6),
        ('PB', 'Ferozepur', 7),
        ('PB', 'Gurdaspur', 8),
        ('PB', 'Hoshiarpur', 9),
        ('PB', 'Jalandhar', 10),
        ('PB', 'Kapurthala', 11),
        ('PB', 'Ludhiana', 12),
        ('PB', 'Malerkotla', 13),
        ('PB', 'Mansa', 14),
        ('PB', 'Moga', 15),
        ('PB', 'Pathankot', 16),
        ('PB', 'Patiala', 17),
        ('PB', 'Rupnagar', 18),
        ('PB', 'S.A.S Nagar', 19),
        ('PB', 'Sangrur', 20),
        ('PB', 'Shahid Bhagat Singh Nagar', 21),
        ('PB', 'Sri Muktsar Sahib', 22),
        ('PB', 'Tarn Taran', 23),
        ('RJ', 'Ajmer', 1),
        ('RJ', 'Alwar', 2),
        ('RJ', 'Banswara', 3),
        ('RJ', 'Baran', 4),
        ('RJ', 'Barmer', 5),
        ('RJ', 'Bharatpur', 6),
        ('RJ', 'Bhilwara', 7),
        ('RJ', 'Bikaner', 8),
        ('RJ', 'Bundi', 9),
        ('RJ', 'Chittorgarh', 10),
        ('RJ', 'Churu', 11),
        ('RJ', 'Dausa', 12),
        ('RJ', 'Dholpur', 13),
        ('RJ', 'Dungarpur', 14),
        ('RJ', 'Ganganagar', 15),
        ('RJ', 'Hanumangarh', 16),
        ('RJ', 'Jaipur', 17),
        ('RJ', 'Jaisalmer', 18),
        ('RJ', 'Jalore', 19),
        ('RJ', 'Jhalawar', 20),
        ('RJ', 'Jhunjhunu', 21),
        ('RJ', 'Jodhpur', 22),
        ('RJ', 'Karauli', 23),
        ('RJ', 'Kota', 24),
        ('RJ', 'Nagaur', 25),
        ('RJ', 'Pali', 26),
        ('RJ', 'Pratapgarh', 27),
        ('RJ', 'Rajsamand', 28),
        ('RJ', 'Sawai Madhopur', 29),
        ('RJ', 'Sikar', 30),
        ('RJ', 'Sirohi', 31),
        ('RJ', 'Tonk', 32),
        ('RJ', 'Udaipur', 33),
        ('SK', 'Gangtok', 1),
        ('SK', 'Gyalshing', 2),
        ('SK', 'Mangan', 3),
        ('SK', 'Namchi', 4),
        ('SK', 'Pakyong', 5),
        ('SK', 'Soreng', 6),
        ('TN', 'Ariyalur', 1),
        ('TN', 'Chengalpattu', 2),
        ('TN', 'Chennai', 3),
        ('TN', 'Coimbatore', 4),
        ('TN', 'Cuddalore', 5),
        ('TN', 'Dharmapuri', 6),
        ('TN', 'Dindigul', 7),
        ('TN', 'Erode', 8),
        ('TN', 'Kallakurichi', 9),
        ('TN', 'Kanchipuram', 10),
        ('TN', 'Kanniyakumari', 11),
        ('TN', 'Karur', 12),
        ('TN', 'Krishnagiri', 13),
        ('TN', 'Madurai', 14),
        ('TN', 'Mayiladuthurai', 15),
        ('TN', 'Nagapattinam', 16),
        ('TN', 'Namakkal', 17),
        ('TN', 'Perambalur', 18),
        ('TN', 'Pudukkottai', 19),
        ('TN', 'Ramanathapuram', 20),
        ('TN', 'Ranipet', 21),
        ('TN', 'Salem', 22),
        ('TN', 'Sivaganga', 23),
        ('TN', 'Tenkasi', 24),
        ('TN', 'Thanjavur', 25),
        ('TN', 'The Nilgiris', 26),
        ('TN', 'Theni', 27),
        ('TN', 'Thiruvallur', 28),
        ('TN', 'Thiruvarur', 29),
        ('TN', 'Tiruchirappalli', 30),
        ('TN', 'Tirunelveli', 31),
        ('TN', 'Tirupathur', 32),
        ('TN', 'Tiruppur', 33),
        ('TN', 'Tiruvannamalai', 34),
        ('TN', 'Tuticorin', 35),
        ('TN', 'Vellore', 36),
        ('TN', 'Villupuram', 37),
        ('TN', 'Virudhunagar', 38),
        ('TS', 'Adilabad', 1),
        ('TS', 'Bhadradri Kothagudem', 2),
        ('TS', 'Hanumakonda', 3),
        ('TS', 'Hyderabad', 4),
        ('TS', 'Jagitial', 5),
        ('TS', 'Jangoan', 6),
        ('TS', 'Jayashankar Bhupalapally', 7),
        ('TS', 'Jogulamba Gadwal', 8),
        ('TS', 'Kamareddy', 9),
        ('TS', 'Karimnagar', 10),
        ('TS', 'Khammam', 11),
        ('TS', 'Kumuram Bheem Asifabad', 12),
        ('TS', 'Mahabubabad', 13),
        ('TS', 'Mahabubnagar', 14),
        ('TS', 'Mancherial', 15),
        ('TS', 'Medak', 16),
        ('TS', 'Medchal Malkajgiri', 17),
        ('TS', 'Mulugu', 18),
        ('TS', 'Nagarkurnool', 19),
        ('TS', 'Nalgonda', 20),
        ('TS', 'Narayanpet', 21),
        ('TS', 'Nirmal', 22),
        ('TS', 'Nizamabad', 23),
        ('TS', 'Peddapalli', 24),
        ('TS', 'Rajanna Sircilla', 25),
        ('TS', 'Ranga Reddy', 26),
        ('TS', 'Sangareddy', 27),
        ('TS', 'Siddipet', 28),
        ('TS', 'Suryapet', 29),
        ('TS', 'Vikarabad', 30),
        ('TS', 'Wanaparthy', 31),
        ('TS', 'Warangal', 32),
        ('TS', 'Yadadri Bhuvanagiri', 33),
        ('TR', 'Dhalai', 1),
        ('TR', 'Gomati', 2),
        ('TR', 'Khowai', 3),
        ('TR', 'North Tripura', 4),
        ('TR', 'Sepahijala', 5),
        ('TR', 'South Tripura', 6),
        ('TR', 'Unakoti', 7),
        ('TR', 'West Tripura', 8),
        ('UP', 'Agra', 1),
        ('UP', 'Aligarh', 2),
        ('UP', 'Ambedkar Nagar', 3),
        ('UP', 'Amethi', 4),
        ('UP', 'Amroha', 5),
        ('UP', 'Auraiya', 6),
        ('UP', 'Ayodhya', 7),
        ('UP', 'Azamgarh', 8),
        ('UP', 'Baghpat', 9),
        ('UP', 'Bahraich', 10),
        ('UP', 'Ballia', 11),
        ('UP', 'Balrampur', 12),
        ('UP', 'Banda', 13),
        ('UP', 'Barabanki', 14),
        ('UP', 'Bareilly', 15),
        ('UP', 'Basti', 16),
        ('UP', 'Bhadohi', 17),
        ('UP', 'Bijnor', 18),
        ('UP', 'Budaun', 19),
        ('UP', 'Bulandshahr', 20),
        ('UP', 'Chandauli', 21),
        ('UP', 'Chitrakoot', 22),
        ('UP', 'Deoria', 23),
        ('UP', 'Etah', 24),
        ('UP', 'Etawah', 25),
        ('UP', 'Farrukhabad', 26),
        ('UP', 'Fatehpur', 27),
        ('UP', 'Firozabad', 28),
        ('UP', 'Gautam Buddha Nagar', 29),
        ('UP', 'Ghaziabad', 30),
        ('UP', 'Ghazipur', 31),
        ('UP', 'Gonda', 32),
        ('UP', 'Gorakhpur', 33),
        ('UP', 'Hamirpur', 34),
        ('UP', 'Hapur', 35),
        ('UP', 'Hardoi', 36),
        ('UP', 'Hathras', 37),
        ('UP', 'Jalaun', 38),
        ('UP', 'Jaunpur', 39),
        ('UP', 'Jhansi', 40),
        ('UP', 'Kannauj', 41),
        ('UP', 'Kanpur Dehat', 42),
        ('UP', 'Kanpur Nagar', 43),
        ('UP', 'Kasganj', 44),
        ('UP', 'Kaushambi', 45),
        ('UP', 'Kheri', 46),
        ('UP', 'Kushi Nagar', 47),
        ('UP', 'Lalitpur', 48),
        ('UP', 'Lucknow', 49),
        ('UP', 'Maharajganj', 50),
        ('UP', 'Mahoba', 51),
        ('UP', 'Mainpuri', 52),
        ('UP', 'Mathura', 53),
        ('UP', 'Mau', 54),
        ('UP', 'Meerut', 55),
        ('UP', 'Mirzapur', 56),
        ('UP', 'Moradabad', 57),
        ('UP', 'Muzaffarnagar', 58),
        ('UP', 'Pilibhit', 59),
        ('UP', 'Pratapgarh', 60),
        ('UP', 'Prayagraj', 61),
        ('UP', 'Rae Bareli', 62),
        ('UP', 'Rampur', 63),
        ('UP', 'Saharanpur', 64),
        ('UP', 'Sambhal', 65),
        ('UP', 'Sant Kabeer Nagar', 66),
        ('UP', 'Shahjahanpur', 67),
        ('UP', 'Shamli', 68),
        ('UP', 'Shravasti', 69),
        ('UP', 'Siddharth Nagar', 70),
        ('UP', 'Sitapur', 71),
        ('UP', 'Sonbhadra', 72),
        ('UP', 'Sultanpur', 73),
        ('UP', 'Unnao', 74),
        ('UP', 'Varanasi', 75),
        ('UK', 'Almora', 1),
        ('UK', 'Bageshwar', 2),
        ('UK', 'Chamoli', 3),
        ('UK', 'Champawat', 4),
        ('UK', 'Dehradun', 5),
        ('UK', 'Haridwar', 6),
        ('UK', 'Nainital', 7),
        ('UK', 'Pauri Garhwal', 8),
        ('UK', 'Pithoragarh', 9),
        ('UK', 'Rudra Prayag', 10),
        ('UK', 'Tehri Garhwal', 11),
        ('UK', 'Udam Singh Nagar', 12),
        ('UK', 'Uttar Kashi', 13),
        ('WB', '24 Paraganas North', 1),
        ('WB', '24 Paraganas South', 2),
        ('WB', 'Alipurduar', 3),
        ('WB', 'Bankura', 4),
        ('WB', 'Birbhum', 5),
        ('WB', 'Coochbehar', 6),
        ('WB', 'Darjeeling', 7),
        ('WB', 'Dinajpur Dakshin', 8),
        ('WB', 'Dinajpur Uttar', 9),
        ('WB', 'Hooghly', 10),
        ('WB', 'Howrah', 11),
        ('WB', 'Jalpaiguri', 12),
        ('WB', 'Jhargram', 13),
        ('WB', 'Kalimpong', 14),
        ('WB', 'Kolkata', 15),
        ('WB', 'Maldah', 16),
        ('WB', 'Medinipur East', 17),
        ('WB', 'Medinipur West', 18),
        ('WB', 'Murshidabad', 19),
        ('WB', 'Nadia', 20),
        ('WB', 'Paschim Bardhaman', 21),
        ('WB', 'Purba Bardhaman', 22),
        ('WB', 'Purulia', 23)
    ) AS d(state_code, district_name, display_order)
    INNER JOIN master_states ms
        ON ms.country_id = v_country_id
       AND ms.code = d.state_code
    ON CONFLICT (state_id, name) DO UPDATE
    SET display_order = EXCLUDED.display_order,
        is_active = EXCLUDED.is_active,
        updated_at = CURRENT_TIMESTAMP;
END $$;

-- Remove the former 400 × 400 minimum-dimension restriction.
ALTER TABLE public.prelaunch_photos
    DROP CONSTRAINT IF EXISTS
    chk_prelaunch_photo_dimensions;

-- Retain basic data-integrity validation without imposing image quality rules.
ALTER TABLE public.prelaunch_photos
    ADD CONSTRAINT chk_prelaunch_photo_dimensions
    CHECK (
        width_px > 0
        AND height_px > 0
    );

COMMIT;
