<?php

declare(strict_types=1);

namespace App\Services\Admin\Audit;

final class AdminAuditAction
{
    public const LOGIN_SUCCESS =
    'ADMIN_LOGIN_SUCCESS';

    public const LOGIN_FAILURE =
    'ADMIN_LOGIN_FAILURE';

    public const LOGOUT =
    'ADMIN_LOGOUT';

    public const ADMIN_CREATED =
    'ADMIN_CREATED';

    public const INVITATION_QUEUED =
    'ADMIN_INVITATION_QUEUED';

    public const INVITATION_RESENT =
    'ADMIN_INVITATION_RESENT';

    public const INVITATION_ACCEPTED =
    'ADMIN_INVITATION_ACCEPTED';

    public const INVITATION_REJECTED =
    'ADMIN_INVITATION_REJECTED';

    public const ADMIN_SUSPENDED =
    'ADMIN_SUSPENDED';

    public const ADMIN_REACTIVATED =
    'ADMIN_REACTIVATED';

    public const ACCESS_DENIED =
    'ADMIN_ACCESS_DENIED';

    public const MEMBER_PHOTO_APPROVED =
    'MEMBER_PHOTO_APPROVED';

    public const MEMBER_PHOTO_REJECTED =
    'MEMBER_PHOTO_REJECTED';

    public const MEMBER_PHOTOS_BULK_APPROVED =
    'MEMBER_PHOTOS_BULK_APPROVED';

    public const FIELD_OFFICER_CREATED =
    'FIELD_OFFICER_CREATED';

    public const FIELD_OFFICER_UPDATED =
    'FIELD_OFFICER_UPDATED';

    public const FIELD_OFFICER_ACTIVATED =
    'FIELD_OFFICER_ACTIVATED';

    public const FIELD_OFFICER_DEACTIVATED =
    'FIELD_OFFICER_DEACTIVATED';

    public const FIELD_OFFICER_ACTIVATION_DENIED =
    'FIELD_OFFICER_ACTIVATION_DENIED';

    public const PRELAUNCH_PROFILE_APPROVED =
    'PRELAUNCH_PROFILE_APPROVED';

    public const PRELAUNCH_PROFILE_REJECTED =
    'PRELAUNCH_PROFILE_REJECTED';

    public const PRELAUNCH_PROFILE_CONTACT_UPDATED =
    'PRELAUNCH_PROFILE_CONTACT_UPDATED';

    public const PRELAUNCH_PHOTO_STATUS_CHANGED =
    'PRELAUNCH_PHOTO_STATUS_CHANGED';

    private function __construct() {}
}
