<?php

declare(strict_types=1);

namespace App\Support;

/**
 * Reads the release version generated by the deployment process.
 *
 * The deployment script writes the Git release tag to:
 *
 * writable/release-version
 *
 * The application never runs Git commands at request time.
 */
final class ReleaseVersion
{
    private const VERSION_FILE =
    'release-version';

    /**
     * Return the deployed semantic version.
     *
     * An unavailable or invalid version fails closed to an empty
     * value, causing the footer component to render nothing.
     */
    public static function current(): string
    {
        $versionFile =
            WRITEPATH
            . self::VERSION_FILE;

        if (
            !is_file($versionFile)
            || !is_readable($versionFile)
        ) {
            return '';
        }

        $contents =
            file_get_contents(
                $versionFile
            );

        if ($contents === false) {
            return '';
        }

        $version = trim(
            $contents
        );

        /*
         * Production releases use strict vMAJOR.MINOR.PATCH tags.
         *
         * Examples:
         *
         * v1.0.0
         * v2.4.12
         */
        if (
            preg_match(
                '/^v[0-9]+\.[0-9]+\.[0-9]+$/',
                $version
            ) !== 1
        ) {
            return '';
        }

        return $version;
    }
}
